### ISSUE TITLE
Is the Android module functional. If so how can I compile it?

### ISSUE THREAD

**Issue by fahad86** [chrisribe/ti-firebase#13]
Whilst trying to compile the android module I get an error:
`[java] java.io.FileNotFoundException: /Users/xxxx/xxxx/ti-firebase/android/build/generated/json/org/appcelerator/titanium/bindings/ti-firebase.json (No such file or directory)`
The build completes though, successfully.

And whilst trying to run my project with the compiled module I get the error:
`[ERROR] :  Module ti.firebase version 1.0.0 is missing bindings json file
`

**Comment by chrisribe** [comment]
Hi fahad86,

No the android version has not been developed only setup.
I am looking into implementing this in the future.
Chris
