### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by AppWerft** [chrisribe/ti-firebase#14]
Hi,

I don't see sense making sources ...

**Comment by chrisribe** [comment]
Hi,

As in why are there android references in the library if it does not work under android?
If that is your question, I started working on that but got pulled away from the project, so it's on ice...

Your welcome to give it a shot...
Chris

**Comment by AppWerft** [comment]
I have started. Main problem is currenty the usage  playservices.json

**Comment by chrisribe** [comment]
Thanks @AppWerft looks promising leaving a reference to your project here.
https://github.com/AppWerft/Ti.Firebase
