### ISSUE TITLE
[FIRApp configure] could not find a valid GoogleService-Info.plist in your project

### ISSUE THREAD

**Issue by miguelsignes** [chrisribe/ti-firebase#20]
Hello, i have a Alloy project and put a in a app/platforms/ios the GoogleService info but it doesn't work.
What i'm doing wrong?

**Comment by miguelsignes** [comment]
Ok, no issue, in Alloy Project the GoogleServiceInfo.plist must be in app/assets/platform/iphone

**Comment by pavlidismi** [comment]
Hello i have the same problem i tried to add the GoogleServiceInfo.plist in the path above but nothing

**Comment by miguelsignes** [comment]
Put the GoogleServiceInfo.plist in App/assets/iphone.
M

**Comment by chrisribe** [comment]
@pavlidismi did you get it to work ?

**Comment by Wingee** [comment]
I've tried it in various places and it still says it can't find the file. Did anybody find the correct location for it in an alloy project??

**Comment by Marchief** [comment]
Finally found the right location on 6.1.2.GA
app/assets/iphone

**Comment by chrisribe** [comment]
Thanks @marchief !!
